# Site settings
title: Sabina Adhikari
email: sabinaadhikari2023@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page. Here, you will learn about my life journey, work experiences while I was in academia and in industry. Leave a comment if you like to learn more about any aspect of my life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: https://www.linkedin.com/in/sabina20/

# Build settings
markdown: kramdown
